### ISSUE TITLE
Funds missing from my country (Brazil)

### ISSUE THREAD

**Issue by fmgithub2017** [alvarobartt/investpy#107]
I couldn't find several funds from Brazil.

Below it is an example of fund which the command `investpy.get_funds_list(country='brazil')` does not find:
fund name:    Arx Elbrus Debêntures Incentivadas Fundo De Investimento Multimercado Crédito Privado
Investing.com link:    https://www.investing.com/funds/arx-elbrus-debentures-incentivadas

Nonetheless, your module investpy is fantastic, thank you for the work.

**Comment by fmgithub2017** [comment]
OBS: One issue might be the special character from "Debêntures"

**Comment by alvarobartt** [comment]
Hi @fmgithub2017, I did some research and found out that the missing fund from Brazil is not even indexed in the Brazil Funds main site of Investing.com, from where the static data is retrieved.

So on, currently that fund can not be retrieved using investpy's fund functions, as Investing.com told me, they are improving the funds section and some major changes will be done over it. Until that change is applied, you can use Investing.com search engine via the function `investpy.search(text, filters, n_results)`, which can find any product indexed in Investing.com.

Sample code attached below:

```python
import investpy

missing_fund = 'Arx Elbrus Debêntures Incentivadas Fundo De Investimento Multimercado Crédito Privado'
search_results = investpy.search(text=missing_fund, filters=['funds'])

for search_result in search_results:
    print(search_result)

>>> {"id_": 1152252, "name": "Arx Elbrus Deb\u00eantures Incentivadas Fundo De Investimento Multimercado Cr\u00e9dito Privado", "symbol": "0P0001EF48", "country": "brazil", "tag": "arx-elbrus-debentures-incentivadas", "pair_type": "fund", "exchange": "BM&FBovespa"}
```

Thank you for reporting this issue, feel free to open as many as you need! :star: :octocat:

**Comment by fmgithub2017** [comment]
@alvarobartt , thank you very much for the effort and reply! I will stay tuned. Cheers
