### ISSUE TITLE
ETF Information

### ISSUE THREAD

**Issue by firmai** [alvarobartt/investpy#114]
Hey mate, you know what would be useful, specifying whether or not an ETF is leveraged, and the x leverage (2,3,4). I don't know if it is currently available from your scraping source?

**Comment by lefig** [comment]
Any further ETF support would be most welcome.

**Comment by alvarobartt** [comment]
Thank you @firmai! Currently I am including new functionalities and fixing some issues so, could you please send me the Investing.com page where the ETFs leverage information is? That would ease my job a lot since currently I do not have that much time. Thank you again!

**Comment by alvarobartt** [comment]
Hi again @firmai, I have been doing some research on which information does Investing.com provide for ETFs and **I have not been able to find the leverage information**. So currently **this issue will not be worked on**, anyways, feel free to include the URL or the reference if you find that information at Investing.com. Thank you!
