### ISSUE TITLE
US Dollar Index Futures - DX

### ISSUE THREAD

**Issue by matiasjr** [alvarobartt/investpy#118]
Primero, lo siento si mi pregunta está en el lugar equivocado.

Estoy buscando los datos recientes del "Futuro del índice del dólar estadounidense"
 usando la función:

`investpy.search(text = "US Dollar Index", n_results=None, filters=None)`

Tengo los siguientes comentarios:

> 0,"{""id_"": 8827, ""name"": ""US Dollar Index Futures"", ""symbol"": ""DX"", ""country"": ""united states"", ""tag"": ""us-dollar-index"", ""pair_type"": ""fxfuture"", ""exchange"": ""ICE""}"

Solo pude localizar el índice DXY y no el índice DX.

¿Cómo obtendría los datos para el Index DX?

**Comment by alvarobartt** [comment]
¡Hola @matiasjr! 

No sé si estoy del todo seguro de haber entendido tu pregunta, puesto que mencionas que no puedes encontrar el índice `DX` aunque en el fragmento adjunto si está disponible dicho índice. Aún así, a continuación te adjunto un fragmento de código que hace uso de la función `investpy.search()` para la búsqueda de productos en Investing.com.

![Screenshot from 2020-03-15 11-57-42](https://user-images.githubusercontent.com/36760800/76700201-8aae1680-66b5-11ea-811a-cd84f65b57bc.png)

_Nota: en el fragmento que has adjuntado, tan solo aparece la primera salida de la función, pero como puedes ver, la función devuelve todos los resultados encontrados, no solo el primero._

Espero haberte ayudado, cualquier duda o problema que tengas no dudes en abrir tantos _issues_ como consideres necesario. ¡Un saludo!
