### ISSUE TITLE
Tickers on investing.com but not in investpy

### ISSUE THREAD

**Issue by ymyke** [alvarobartt/investpy#129]
These 2 tickers are online available but not via the package:

Twilio: https://www.investing.com/equities/twilio-inc-a

```
[x for x in stocks_dir if x["isin"] and "US90138F1021" in x["isin"]]
[{'country': 'mexico',
  'name': 'Twilio',
  'full_name': 'Twilio Inc',
  'isin': 'US90138F1021',
  'currency': 'MXN',
  'symbol': 'TWLO'}]
# Only mexico, but it's listed on NYSE.
```

Shopify: https://www.investing.com/equities/shopify-inc

```
[x for x in stocks_dir if x["isin"] and "CA82509L1076" in x["isin"]]
[{'country': 'canada',
  'name': 'Shopify Inc',
  'full_name': 'Shopify Inc',
  'isin': 'CA82509L1076',
  'currency': 'CAD',
  'symbol': 'SHOP'}]
# Only canada, but it's listed on NYSE...
```

**Comment by alvarobartt** [comment]
Hi again @ymyke,

as you can see in the [FAQs](https://investpy.readthedocs.io/faq.html#what-do-i-do-if-the-financial-product-i-am-looking-for-is-not-indexed-in-investpy), some Investing.com products are not properly listed by Investing.com so some data can not be stored as static data. So as to solve this, there is a function (which is being improved so as to be stable in the next investpy's release) that is called: `investpy.search(text, filters=None, n_results=None)`. 

There is a wiki page with all the function usage, currently just available in the investpy's development version: https://github.com/alvarobartt/investpy/wiki/investpy.search()

You can either use the current version which implements the function as it follows: `investpy.search(text, filters=None, n_results=None)` or the development one as previously mentioned which implements the function as: `investpy.search(text, products=None, countries=None, n_results=None)`.

**Note**: to install the development version just use the following command: `pip install git+https://github.com/alvarobartt/investpy.git@developer`

**Comment by alvarobartt** [comment]
Here I attach you a screenshot of the answer to your question using the development version of **investpy** in a Jupyter Notebook:

![image](https://user-images.githubusercontent.com/36760800/77579276-5408a500-6eda-11ea-8320-6eb77e3e4f63.png)

Hope this helped you, thank you!

**Comment by ymyke** [comment]
Thanks, @alvarobartt. I understand that I can use the search function to find meta data for those symbols, but, how do I get the historical data for such a symbol?

```
investpy.get_stock_historical_data(stock="SHOP", country="united states", from_date="01/01/2019", to_date="31/1/2019")

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
c:\code\fignal\_sandbox\investing.py in 
----> 1 investpy.get_stock_historical_data(stock="SHOP", country="united states", from_date="01/01/2019", to_date="31/1/2019")

~\Anaconda3\envs\fignal\lib\site-packages\investpy\stocks.py in get_stock_historical_data(stock, country, from_date, to_date, as_json, order, interval)
    510 
    511     if unidecode.unidecode(stock) not in [unidecode.unidecode(value.lower()) for value in stocks['symbol'].tolist()]:
--> 512         raise RuntimeError("ERR#0018: stock " + stock + " not found, check if it is correct.")
    513 
    514     symbol = stocks.loc[(stocks['symbol'].str.lower() == stock).idxmax(), 'symbol']

RuntimeError: ERR#0018: stock shop not found, check if it is correct.
```

**Comment by alvarobartt** [comment]
Hi @ymyke, in order to retrieve data from those symbols, you should do this with every search_result object returned from the `investpy.search()` function:

```python
for search_result in search_results:
    data = search_result.retrieve_historical_data(from_date="01/01/2019", to_date="31/01/2019")
```

Since, as I previously mentioned, some data is not stored under investpy's static files, which means that you need to use the search function and the search object. Hope this helped you!

**Comment by ymyke** [comment]
Got it, thanks. I didn't know I could retrieve data from the search results objects.
