### ISSUE TITLE
ConnectionError: ERR#0015: error 406, try again later.

### ISSUE THREAD

**Issue by sdiamar** [alvarobartt/investpy#149]
Hi Álvaro,

Congratulations for your job. 
I am working with investpy to extract all historical data from a few markets. 
I have saved all the tickers of Spain, France, Germany and Italy markets in an excel file. 
With a loop “for”, it goes over the tickers and saves, in another excel, all historical data of each ones. It worked well in the first time. All historical data had been saved correctly on my computer.  In the second time, the error showed up. The error appears in those codes:

investpy.stocks.get_stock_historical_data(stock, country, from_date, to_date, as_json=False, order='ascending', interval='Daily')

investpy.stocks.get_stock_dividends(stock, country)

investpy.stocks.get_stock_information(stock, country)

Now, it doesn’t let me run any request of this type, even without a single value. Other codes, like tickers or countries lists, yes they work. 
Summarizing, since yesterday, I get this error: connection error, and doesn’t let me work. I think that investing have introduced me in a blacklist for all repeated requests in so few minutes. 

How can I fix it? Is it possible?

Thank you so much. 
Sara

**Comment by ymyke** [comment]
Hi Sara, if I my chime in: I recommend being nice with the web sites you are scapring. Scrapinghub has a good overview (geared towards Scrapy, but easily adaptable to other situations):
https://blog.scrapinghub.com/2016/08/25/how-to-crawl-the-web-politely-with-scrapy

Furthermore, I suggest using a cache, e.g. `requests_cache`. (See also #126, however, I am not sure what the outcome there is.)

Best
myke.

**Comment by sdiamar** [comment]
Hi Myke,

Thank you so much. 
Finally, I have solved it using a timeout between a request and the next request (Álvaro's recommendation):

import time

time.sleep(1)

Best.
Sara

**Comment by alvarobartt** [comment]
Hi @sdiamar! As we already discussed by mail, this is an issue related to Investing.com limitations, so the way to solve it (as you mentioned) is setting a timeout between 1 and 2 seconds, since I tested a massive amount of requests to Investing.com with a timeout of 1.5 seconds and I got no restriction at all. As you mentioned, the following piece of code is the one you need to include so as to solve this:

```
import time
time.sleep(1.5) # After each request, inside a FOR loop for example
```

Also, I considered including the timeout by default inside all the stock data retrieval functions, but that would have disadvantaged the users that just send a few requests.

So I propose you both @sdiamar and @ymyke to use timeouts, since caches just work if you are requesting the same data over and over.

Thank you!

**Comment by ymyke** [comment]
Sounds good!

As an alternative, you could consider detecting the error and then waiting.

Here's how I do it with alphavantage, for your reference:

```
    df = None
    while df is None:
        try:
            df, _ = _ts.get_quote_endpoint(ticker)
        except ValueError as e:
            if "API call frequency" in str(e):
                logger.info("API wants us to wait, so we wait 61 seconds and then try again")
                time.sleep(61)
            else:
                raise
```

(Alphavantage blocks for 1 minute whene there are too many requests.)

**Comment by mikylucky** [comment]
Hi @sdiamar, I'm facing the same issue. How long have you been blocked for before being allowed make calls again?

**Comment by sdiamar** [comment]
Hi Michele, I have been blocked by a whole day. Then, I used the time sleep and it worked for me correctly. 
Lucky!

**Comment by mikylucky** [comment]
@sdiamar thanks for the quick feedback! I'll try again tomorrow then
