### ISSUE TITLE
Retrieve ETF Volume

### ISSUE THREAD

**Issue by mreismendes** [alvarobartt/investpy#150]
I noticed that `investpy.etfs.get_etf_historical_data` doesn't retrieve volume even though that information is available on the Investing.com.

I think this improvement could be useful for many users like me, I'm trying to retrieve Brazilian ETFs prices and volumes exchanged at B3.

By the way, thank you for your superb work with this library, its functionalities help me a lot!

**Comment by alvarobartt** [comment]
Hi @mreismendes, sorry for taking too long to contact you, but I have been pretty busy this past months. I will try to solve this issue tomorrow, since it is considered a minor issue, with a fast and easy solving. Please stay tuned, thank you for your support and patience!

**Comment by mreismendes** [comment]
Don't worry, you've been doing a great job here!

Thanks for considering my request

**Comment by alvarobartt** [comment]
Hi @mreismendes, it has been already solved, thanks for your contribution! __Note that currently it is just available on the developer version__ which you can install with the following command:

```
pip install git+https://github.com/alvarobartt/investpy.git@developer
```

__Thank you! Remember to star the repo if you found it useful and follow me at GitHub so as to get notified of all the updates!__
