### ISSUE TITLE
investpy.get_stock_information generates incorrect url

### ISSUE THREAD

**Issue by markus080402** [alvarobartt/investpy#153]
Hi,

The following function seem to generate incorrect url and hence "error 404" is returned:

```
import investpy
investpy.get_stock_information('TS', 'argentina', as_json=False)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\investpy\stocks.py", line 1075, in get_stock_information
    raise ConnectionError("ERR#0015: error " + str(req.status_code) + ", try again later.")
ConnectionError: ERR#0015: error 404, try again later.

```
We can see that the symbol 'TS' is available in 'argentina'

```
country_stocks=investpy.stocks.get_stocks(country='argentina')  
print(country_stocks.loc[country_stocks['symbol'] == 'TS'])

   country     name full_name          isin currency symbol
0  argentina  Tenaris   Tenaris  LU0156801721      ARS     TS

```

Investpy generates the url:
https://www.investing.com/equities/tenaris?cid=13302

However, the url should probably be:
https://www.investing.com/equities/tenaris-sa?cid=13302 

Regards,
Markus

**Comment by markus080402** [comment]
Here is another stock that generates incorrect url:

`investpy.stocks.get_stock_company_profile(stock='RBCO11', country='brazil')
`
It generates the following url which doesn't work:
 https://www.investing.com/equities/rb-capital-office-income-company-profile

Probably it should be something like:
https://www.investing.com/equities/rb-capital-off-income-fundo-de-inv

**Comment by markus080402** [comment]
The following also url also doesn't work:

>>> investpy.stocks.get_stock_company_profile(stock='ZYDS', country='india')
{'url': 'https://www.investing.com/equities/zydus-wellness-company-profile', 'desc': "Zydus Wellness Limited is an integrated consumer company. ......"}
>>>

**Comment by alvarobartt** [comment]
Hi @markus080402, thanks for also reporting this issue! All the problems are related to investpy static data since it has not been updated in so long, please subscribe to #134, since all the static files should be updated. Also, note that in the last problem you mention, the URL: https://www.investing.com/equities/zydus-wellness-company-profile works properly, please check it out again.

__Thank you! Remember to star the repo if you found it useful and follow me at GitHub so as to get notified of all the updates!__

**Comment by markus080402** [comment]
HI @alvarobartt ,

Great, I will start to use the developer branch to get the latest fixes and functionality.

Question:
Which files/functions fetch and store the static data into stocks.csv?

Thanks

**Comment by markus080402** [comment]
Hi @alvarobartt 

I just tried with latest version on the developer branch and still getting an incorrect url for:

https://www.investing.com/equities/tenaris?cid=13302

Which should probably be:

https://www.investing.com/equities/tenaris-sa?cid=13302

I wonder if not the solution suggested in https://github.com/alvarobartt/investpy/issues/154 might help also for this issue since the problems with non-unique 3-tuples (as described in https://github.com/alvarobartt/investpy/issues/154 ) can cause problems in several functions?

Thanks and regards,
Markus

**Comment by alvarobartt** [comment]
Hi @markus080402 as I already told you, I still need to update the static data (which in this case is `stocks.csv`) since I need to include the `stock_exchange` parameter, etc. so one the data is updated, the tags will also be updated, since that error is due to an old url tag. Thank you for your patience!

**Comment by markus080402** [comment]
Hi @alvarobartt ,

Sorry about that, I read your previous message as stocks.csv was already updated.

How can an investpy user update the stocks.csv ? Which code to run?

Thanks and regards!

**Comment by alvarobartt** [comment]
The process of generating `stocks.csv` takes some days to run, so I think that there is no reason it should be available, you may need to wait for some days until it is completely generated. After I release the 1.0 version, I will find a good and cheap server so as to host the data which will be updated once a week and will create a function to download and update it from Investing.com. Thank you!

**Comment by markus080402** [comment]
Hi @alvarobartt ,

Would it be possible to share the code privately? I have made something that works pretty well.

Thanks and regards,
Markus

**Comment by alvarobartt** [comment]
Hi @markus080402, of course, I will share the code with you. I need to clean it a little bit, since I just run private tests, so the code is a little bit messy. Once the data is updated and uploaded I will share the code with you from GitHub. Thank you for your support!

**Comment by diogoraucci** [comment]
Hi @alvarobartt ,

I juste report another error.
Here is another stock that generates incorrect data:
invt.stocks.get_stock_company_profile('PTBL3', country=('brazil'), language='en'), index=[0]
ConnectionError: ERR#0015: error 404, try again later.

(https://www.investing.com/equities/pbg-sa-company-profile?cid=18761)

The company Profile is there , in the website, but i cant get him whit python.


I'm newbie in programming, if you have any guidance, please help me.
Thanks

sorry for my bad english
