### ISSUE TITLE
technical_factors should be technical_indicators in technical.py

### ISSUE THREAD

**Issue by ymyke** [alvarobartt/investpy#156]
Check the examples section in the docstring of `technical_indicators` in `technical.py`: The function is called `technical_factors` there instead of `technical_indicators`.

**Comment by alvarobartt** [comment]
Hi @ymyke, thanks for spotting that, so you mean that the function should be renamed to `technical_indicators`, like it is the proper name? Thank you!

**Comment by ymyke** [comment]
Yes, here:
https://github.com/alvarobartt/investpy/blob/865d530b22a214e66168ddc22f1139b243d278b4/investpy/technical.py#L57

**Comment by alvarobartt** [comment]
Oh yeah, I spotted that error some weeks ago, it was already changed on the developer version, as you can see in:

https://github.com/alvarobartt/investpy/blob/1fde1252d81391b9cbd61e51c350a471787a996f/investpy/technical.py#L54
