### ISSUE TITLE
Data range in news returning one day early

### ISSUE THREAD

**Issue by ifscher** [alvarobartt/investpy#161]
Hello!

The data range is one day early at the start and finish, but the new is coming in the right range. 
For example, the news from 01/05/2020 is placed as it was from 30/04/2020.

Thanks for your effort by doing this API. It's really awesome.

**Comment by alvarobartt** [comment]
Hi @ifscher, thanks for the kind words! The issue/bug you are describing if I am not wrong was already solved, but it is currently just available on the developer version, which you can easily install with the following command:

```
pip install git+https://github.com/alvarobartt/investpy.git@developer
```

Once you test it, tell me if the issue/bug is solved and I will close the issue, or you can just close the issue one you check if it works. And if it does not I will seek the bug and try to repair it as soon as possible.

__Thank you! Remember to star the repo if you found it useful and follow me at GitHub so as to get notified of all the updates!__
