### ISSUE TITLE
Missing London ETF instruments

### ISSUE THREAD

**Issue by lefig** [alvarobartt/investpy#166]
Hi there,

We already have a ticket raised regarding missing LSE equities.

But it would seem that we are unable to download any ETF instruments. Today we tried some very popular ones:

VMID | VANGUARD FTSE 250 UCITS ETF
VWRL | VANGUARD FTSE ALL-WORLD UCITS ETF GBP
VUSA | VANGUARD S&P 500 UCITS ETF GBP

But every time we have a missing exception:

try:   
            data = investpy.get_stock_historical_data(stock=symbol,
                                                                country=_country,
                                                                from_date=self.investpy_start_date_time,
                                                                to_date=self.investpy_today_date_time)
        
            #Convert the index to datetime.
            data.index = pd.to_datetime(data.index)
            data.columns = ['Open', 'High', 'Low', 'Close','Volume','Currency']
            data = data.drop(columns=['Currency'])
            data  = data.round({"Open":4, "High":4, "Low":4, "Close":4}) 

        except Exception as ex:
            self.invest_symbols_failed[symbol] = str(ex)
            self.invest_symbols_failed[symbol] = symbol
            print(f"Investing.com: Downloading failed: {symbol}")

Have you actually tested the ETF download API? 

Thank you

**Comment by alvarobartt** [comment]
Hi @lefig I am aware of the previous issue you reported and I am working so as to retrieve all the available data, but the Investing.com listings are really messy and it is quite hard to retrieve all the available ones. Additionally, as I probably mentioned you before, you can install the investpy's developer version and use the function `investpy.search_quotes(text, products, countries)` which uses the Investing.com search engine to find any financial product available at Investing.

To install the developer version of investpy you can use the following command:

```
pip install git+https://github.com/alvarobartt/investpy.git@developer
```

__Thank you! Remember to star the repo if you found it useful and follow me at GitHub so as to get notified of all the updates!__

**Comment by alvarobartt** [comment]
__Here I attach you the referencing Wiki => [investpy.search_quotes](https://github.com/alvarobartt/investpy/wiki/investpy.search_quotes())__

Hope it helps you understand `investpy.search_quotes()` function usage!

**Comment by lefig** [comment]
Thank you for the update.

Most appreciated too.
