### ISSUE TITLE
Suggestion for investpy.stocks.get_stocks_overview() function

### ISSUE THREAD

**Issue by evsv73** [alvarobartt/investpy#177]
When running the investpy.stocks.get_stocks_overview() function I got the following error:

File "C:\ProgramData\Anaconda3\lib\site-packages\investpy\stocks.py", line 1272, in get_stocks_overview
    "turnover": int(turnover),
ValueError: invalid literal for int() with base 10: '4.84B'

I'd suggest adding the following elif clause at line #1262 of investpy\stocks.py file:
#############CODE################
elif turnover.__contains__('B'):
    turnover = float(turnover.replace('B', '').replace(',', '')) * 1e9
#################################
It worked perfectly fine with me.

**Comment by alvarobartt** [comment]
Hi @evsv73, thank you for reporting this bug! Could you please also send me the function call that throws that exception so as to include it on the tests?

Once I can recreate the error I will fix it as soon as possible!

__Thank you again! Remember to star the repo if you found it useful and follow me at GitHub so as to get notified of all the updates!__

**Comment by evsv73** [comment]
Traceback (most recent call last):
  File "d:/PyProjects/scraping/finviz6.py", line 7, in <module>
    my_req = investpy.stocks.get_stocks_overview(country, as_json=False, n_results=100)
  File "C:\ProgramData\Anaconda3\lib\site-packages\investpy\stocks.py", line 1272, in get_stocks_overview
    "turnover": int(turnover),
ValueError: invalid literal for int() with base 10: '3.79B'

**Comment by alvarobartt** [comment]
Hi @evsv73, but which where the parameters that triggered that error?

**Comment by evsv73** [comment]
investpy.stocks.get_stocks_overview('russia', as_json=False, n_results=100)
