### ISSUE TITLE
News.py

### ISSUE THREAD

**Issue by guanm326** [alvarobartt/investpy#186]
Is it possible to use the get_calendar function to get multiple days of data? Like historical economic releases? I tried to populate from_date and to_date from 1990s to 2020, but it always return just a couple days in 1990, never all the way to 2020.

I am doing it via a loop but its no efficient and I make too many queries.

**Comment by traderpedroso** [comment]
> Is it possible to use the get_calendar function to get multiple days of data? Like historical economic releases? I tried to populate from_date and to_date from 1990s to 2020, but it always return just a couple days in 1990, never all the way to 2020.
> 
> I am doing it via a loop but its no efficient and I make too many queries.
``

def dateloop():
  
  
  today = date.today()
  start_date = datetime.date(1991, 1, 1)
  delta = datetime.timedelta(days=1)

  while start_date <= today:
      start_date += delta
      start = start_date.strftime('%d/%m/%Y')
      end = today.strftime('%d/%m/%Y')
      df = investpy.economic_calendar(from_date=start,to_date=end)
      df.to_csv('calendar.csv', mode='a',header=False)
      
      
dateloop()
```

**Comment by traderpedroso** [comment]
> Is it possible to use the get_calendar function to get multiple days of data? Like historical economic releases? I tried to populate from_date and to_date from 1990s to 2020, but it always return just a couple days in 1990, never all the way to 2020.
> 
> I am doing it via a loop but its no efficient and I make too many queries.

better than b4

```python
from datetime import timedelta, date
import investpy  
import pandas as pd
import datetime

delta = datetime.timedelta(days=1)
today = date.today()

def daterange(start_date, end_date):
    for n in range(int((end_date - start_date).days)):
        yield start_date + timedelta(n)

start_date = date(2010, 1, 1)
end_date = today
for single_date in daterange(start_date, end_date):
    deltacalc = single_date
    deltacalc += delta
    df = investpy.economic_calendar(from_date=single_date.strftime('%d/%m/%Y'),to_date=deltacalc.strftime('%d/%m/%Y'))
    df.to_csv('calendar.csv', mode='a', header=False)
    ```

**Comment by alvarobartt** [comment]
Hi @guanm326 and @traderpedroso! 🤗 Could you give me more details regarding this issue so as to solve it? And could you please also chech whether this is still happening in the latest investpy release or not?

``
pip install investpy --upgrade
``

Remember to star the repo, follow me here and on Twitter at https://twitter.com/alvarobartt so as to get notified from all the updates and projects I'm working on! ⭐ :octocat:

**Comment by alvarobartt** [comment]
Hi @guanm326 and @traderpedroso! 🤗 This issue has just been fixed and will be available in the next investpy release which will be the v1.0.2 🔥 

Thanks for your support! You can already use it installing investpy from source with the following command:

```
pip install git+https://github.com/alvarobartt/investpy.git@master
```
