### ISSUE TITLE
Stock missing

### ISSUE THREAD

**Issue by similang** [alvarobartt/investpy#188]
Hi, 

I noticed there're some stocks missing from the  

investpy.get_stocks(country='malaysia').sort_values('full_name')

Attached is the list of stocks missing from Malaysia stock market. 

Also, many thanks for such an awesome package 

![investpy_missing](https://user-images.githubusercontent.com/7208012/86508714-d9beb980-be14-11ea-8f51-8465ecb396d1.PNG)

Another thing I wonder, is it possible to get price from max range in investing.com? 

Thanks from Malaysia.

**Comment by GitHunter0** [comment]
Some Brazilian stocks are also missing. For example, this returns `RuntimeError: ERR#0018: stock brev11 not found, check if it is correct.`
```
investpy.get_stock_historical_data(stock='BREV11',
                                   country='brazil',
                                   interval='Daily',
                                   from_date='01/01/1996',
                                   to_date='17/12/2020',
                                   order = 'descending',
                                   as_json = True)   
```

**Comment by alvarobartt** [comment]
Hi @similang and @GitHunter0, thank you for opening this issue, and sorry for taking so long to answer!

As you both may already know, this is a common issue, as Investing.com data indexing is not that easy to scrape, so some data is missing in the static CSV files under `investpy/resources`. Anyway, there's a functionality which is `investpy.search_quotes()` available in the latest `investpy` releases, which solves this as I included a way to use Investing.com search engine to retrieve the data as you would using Investing.com search engine in the web browser, but through Python.

Here's a wiki on how to use it: https://github.com/alvarobartt/investpy/wiki/investpy.search_quotes()

For more details, please don't hesitate to ask me! :hugs:
