### ISSUE TITLE
Functionality wish - Import economic calendar and economic indicator "price" history

### ISSUE THREAD

**Issue by stefanomorni** [alvarobartt/investpy#192]
Hi Alvaro. 
First of all thank you very much for making this wonderful library available to the public.
I have been looking for a long time for a way to import data from investing.com...a very complete site.

I'm only missing one very interesting functionality, which you might consider adding to the library:
ability to import "economic calendar" and retrieve data history for the indicators available by clicking on the relevant indicator on the website (https://www.investing.com/economic-calendar/).

Again thank you and best regards

Stefano

**Comment by LeonardoRick** [comment]
@alvarobartt is that possible to do? I was looking for something like that too
Thanks

**Comment by alvarobartt** [comment]
Did `investpy.economic_calendar()` function worked for you @stefanomorni, @LeonardoRick?

Here you have [the official API documentation of `investpy.economic_calendar()`](https://investpy.readthedocs.io/_api/news.html#investpy.news.economic_calendar)

I'll be closing this issue, but if this isn't what you expected, please let me know so that I can reopen it! :hugs:

**Comment by LeonardoRick** [comment]
@alvarobartt yes it worked for me!
Thanks a lot

**Comment by stefanomorni** [comment]
Hi Alvaro

 

Yes. It worked fine. Thank you.

 

 

Stefano Morniroli
***@***.***

 

Da: Álvaro Bartolomé ***@***.***> 
Inviato: giovedì, 1 aprile 2021 11:26
A: alvarobartt/investpy ***@***.***>
Cc: stefanomorni ***@***.***>; Mention ***@***.***>
Oggetto: Re: [alvarobartt/investpy] Functionality wish - Import economic calendar and economic indicator "price" history (#192)

 

Did investpy.economic_calendar() function worked for you @stefanomorni <https://github.com/stefanomorni> , @LeonardoRick <https://github.com/LeonardoRick> ?

Here you have the official API documentation of  <https://investpy.readthedocs.io/_api/news.html#investpy.news.economic_calendar> investpy.economic_calendar()

I'll be closing this issue, but if this isn't what you expected, please let me know so that I can reopen it! 🤗
