### ISSUE TITLE
Bug in search_quotes - not find assets without defined country 

### ISSUE THREAD

**Issue by Nicolabo** [alvarobartt/investpy#196]
Hi, 
I noticed that `search_quotes()` function could not find some basic commodities or crypto. It happens because such assets do not have a defined country. For example,

```
investpy.search_quotes(text='gold', products=['commodities'])
```

returns many assets but not the first one which pops up on the webpage (`Gold Futures`).

I run a `post request` on my own for `gold` text, and this is the output:

```
{'pairId': 8830, 'name': 'Gold Futures', 'flag': 'gold', 'link': '/commodities/gold', 'symbol': 'ZG', 'type': 'Commodity - ICE', 'pair_type_raw': 'commodity', 'pair_type': 'commodity', 'countryID': 242, 'sector': 0, 'region': 0, 'industry': 0, 'isCrypto': False, 'exchange': 'ICE', 'exchangeID': 1004}
```

As you can see, the `flag` key contains `gold`, and obviously, such a flag does not exist in `constant.FLAG_FILTERS`.

I create a commit locally that should address this problem, so if you give me the write access, I create a pull request.

**Comment by alvarobartt** [comment]
Sorry for having tackled this issue too late 😩 Anyway, thanks a lot for reporting it @Nicolabo!

I've already solved it and it will be released later this week in the `v1.0.3 release` (including some other bug-fixes and improvements) ✨ 

Remember to star the repo, follow me here and on Twitter at https://twitter.com/alvarobartt so as to get notified from all the updates and projects I'm working on! :star: :octocat:
