### ISSUE TITLE
new.py time zone incorrect!

### ISSUE THREAD

**Issue by Milad137** [alvarobartt/investpy#197]
timezone for GMT is incorrect, as 'GMT': [55, 15, 56]
55 is for UTC without daylight saving time.
Please add 'UTC':[55]
'GMT':[15, 56]

**Comment by alvarobartt** [comment]
Hi @Milad137! 🤗 

Could you tell me the error to reproduce it? I thought I fixed the timezones issue on the v1.0 release, but it seems I did not... 😩 That information can be so useful to me towards fixing it. Thank you!

**Comment by alvarobartt** [comment]
Hi again @Milad137 🤗 I've just removed the UTC timezone from that function so as to avoid misunderstandings! I'll close the issue, but can you still provide me more details? I'll appreciate it!
