### ISSUE TITLE
Trouble getting "world" indexes

### ISSUE THREAD

**Issue by mreismendes** [alvarobartt/investpy#204]
I got in trouble trying to retrieve index data from "world" countries!

**Example 01:**
![image](https://user-images.githubusercontent.com/32521301/90422710-a157ff80-e091-11ea-9a5b-a827cea046f4.png)

**Example 02:**
![image](https://user-images.githubusercontent.com/32521301/90422920-f267f380-e091-11ea-8983-f09490a7f083.png)

What should I do to get those data?

Thank you!

**Comment by Haiwen-Hank** [comment]
You could update investpy/util/constant.py by adding {'country': 'world', 'country_name': 'world'} to the end of index INDEX_COUNTRIES

**Comment by davins90** [comment]
> You could update investpy/util/constant.py by adding {'country': 'world', 'country_name': 'world'} to the end of index INDEX_COUNTRIES

Where i can find this path? thanks

**Comment by davins90** [comment]
i add that but in deploying on heroku it doesn't works. In local instead it works

**Comment by davins90** [comment]
thanks it works now! 👍

**Comment by alvarobartt** [comment]
Closing this as it was already fixed by @se-jaeger in https://github.com/alvarobartt/investpy/pull/217 👍🏻

**Comment by mreismendes** [comment]
I still have the same trouble! Should I do something?
