### ISSUE TITLE
Problem with streamlit + heroku on deploying with "get_index_recente_data"

### ISSUE THREAD

**Issue by davins90** [alvarobartt/investpy#206]
hi,

i’m new to streamlit and i’m trying to make a financial dashboard of the markets. In local the code i created work perfectly but now that I’ve deployed it on Heroku appears a strange error on a string that in local works! I don’t know why this happen… This is the error code that appears:

File "/app/.heroku/python/lib/python3.6/site-packages/streamlit/script_runner.py", line 324, in _run_script exec(code, module.dict) 

**File "/app/first_app.py", line 55, in df_eu = investpy.get_index_recent_data(index='MSCI Europe Net EUR',country='euro zone') # europa** 

File "/app/.heroku/python/lib/python3.6/site-packages/investpy/indices.py", line 251, in get_index_recent_data raise RuntimeError("ERR#0034: country " + country.lower() + " not found, check if it is correct.")

I think the error should be in the first line (line 324) but i don’t know how to solve it.

I’m using these libraries: streamlit pandas numpy investpy urlopen BeautifulSoup4

I was thinking that these should be a problem of the financial library “investpy”, but everywhere it works! How is possible that in local the code works and in deploying is not working?

Heroku sets the region to default US, while i’m in Europe: can this be the problem?

Thanks all

**Comment by alvarobartt** [comment]
Hi @davins90! 🤗 Sorry for taking too long to answer...

Did you got it working? did you solved it? Please just let me know 👍🏻

**Comment by alvarobartt** [comment]
Sorry for taking so long to solve this issue even though it was easy to fix but I though it was already fixed 😩

Thank also @GitHunter0! He/She has been tracking this issue for so long as well as proposing solutions!

To install the latest version with this bug fix as well as some other fixes, please install it as it follows:

```
pip install investpy==1.0.3
```

Remember to star the repository, follow me here at https://github.com/alvarobartt and on Twitter at https://twitter.com/alvarobartt so as to get notified about all the updates and projects I'm working on! :star: :octocat:
