### ISSUE TITLE
How to find out what "id" should be per company in stocks.csv in order to add companies to stocks.csv? 

### ISSUE THREAD

**Issue by markus080402** [alvarobartt/investpy#215]
Hi @alvarobartt and all!

The static file stocks.csv has majority of all stocks from investing.com but some stocks are missing.

stocks.csv has the following fields:
country,    name,    full_name,    tag,   isin,    id,    currency,    symbol

Question:
How do we figure out what "id" should be if we want to add missing companies to stocks.csv?

Thanks and regards,
Markus

**Comment by markus080402** [comment]
Ping @alvarobartt  :)

**Comment by vishalpatil** [comment]
if it's about getting quotes check this https://github.com/alvarobartt/investpy/issues/168

**Comment by markus080402** [comment]
Yes, the search function provides the "id", thanks!

**Comment by markus080402** [comment]
The search function  provides the "id".
