### ISSUE TITLE
Important News! Please read

### ISSUE THREAD

**Issue by alvarobartt** [alvarobartt/investpy#218]
Hi everyone,

the community that we have created with investpy is huge, with a growth with over 250 stars within the last 6 months, I'm far from happy and excited! __So thank you everyone!__ ⭐ 

I have some news, __I just merged some pull requests you guys created so as to improve investpy and I encourage you to do so from now on__, as I don't have that much time for investpy as before, but I will continue developing new features so as that you all can make the best usage out of it.

__This issue is just for dropping below some comments or referred issues that you are most interested in as I will try to tackle those first if I see that you are interested on those.__

Finally I would like to mention that some months ago I created a Twitter account, where I will try to answer investpy questions and give you all some updates on what I'm currently working on, new projects, useful resources, etc.

So as to support me, please __follow me on Twitter at https://twitter.com/alvarobartt__ 👍🏻

Thank you again! See you all in 1 week or so...

P.S.: Remember that you can also support me at https://www.buymeacoffee.com/alvarobartt

**Comment by alvarobartt** [comment]
Also, feel free to create some Pull Requests during the month of October since it is the Hacktoberfest 2020, which is some sort of an open-source competition where you get rewarded for contributing to open-source projects if you complete 4 PRs.

So I think this is a good chance to contribute to investpy and get the chance to win a T-shirt or plant a tree, and of course, contributing to open source so as to make the community grow!

All the information available at https://hacktoberfest.digitalocean.com/

Remember to log-in so that the PRs count!

**Comment by NSSmithPortfolio** [comment]
I'd love to be able to pull technical indicators and moving averages for crypto, such as those on this screen: https://www.investing.com/indices/investing.com-ltc-usd-technical

I'd take any, but ideally could pull the different time frames.

I'd be willing to help tackle it some but just looking at existing code, you are many levels above me (beginner to intermediate).  Tell me how I can help?

**Comment by alvarobartt** [comment]
Hi @NSSmithPortfolio I already closed this as October ended! Thank you for your proposal! 🤗 

Could you please create it on a different new issue so that I can include it in the v1.1 release? Thanks again!
