### ISSUE TITLE
Investpy and Pyinstaller

### ISSUE THREAD

**Issue by ferguswaterhouse** [alvarobartt/investpy#224]
Hi @alvarobartt 

I have created an app using investpy which is awesome btw, just what I was looking for! I am now finally at the stage of packaging the script into an exe file using pyinstaller but I get the following error which seems to be linked to the invespy api:

NotImplementedError: Can't perform this operation for unregistered loader type

If you could help me with this it would be greatly appreciated or is this even possible?

Cheers Fergus

**Comment by MohammedAlawami** [comment]
Hello @ferguswaterhouse 
Did you solve this issue? I'm facing the same problem

**Comment by alvarobartt** [comment]
Hi @ferguswaterhouse, can you provide more details? Is that something that was failing from your side, or was it an `investpy` related issue? Please let me know! 👍🏻 

Can you give me more information so as to reproduce the issue, @MohammedAlawami? Or at least more information so that I can easily reproduce it in order to solve it in case this is an `investpy` related issue of course. Thanks! 🤗

**Comment by MohammedAlawami** [comment]
Hello @alvarobartt Thank you for your support.

After I packaged my program with [pyinstaller](https://github.com/pyinstaller/pyinstaller) and try to run the exe file I get this error 

`
 File "investpy\commodities.py", line 504, in get_commodity_historical_data
 File "pkg_resources\__init__.py", line 1120, in resource_exists
 File "pkg_resources\__init__.py", line 1391, in has_resource
 File "pkg_resources\__init__.py", line 1458, in _has
NotImplementedError: Can't perform this operation for unregistered loader type
`

**Comment by MohammedAlawami** [comment]
@alvarobartt I was able to solve the issue by using an unmerged branch in pyinstaller
Thanks a lot.

**Comment by tuansacer** [comment]
> 
Hello @MohammedAlawami . i found same issue now with pyinstaller 4.6 + investpy 1.0.8

Could you share me your way to fix this one ?
