### ISSUE TITLE
Intraday data

### ISSUE THREAD

**Issue by odufb** [alvarobartt/investpy#227]
As far as I know  only daily weekly and monthly  data availble for the stocks.  is it possible to get intraday data such as 4h 1h 30m etc.

thank you for your great work.

**Comment by legout** [comment]
@alvarobartt 
Intraday data would be a really nice feature. 

It is available using the following link:

For example, this is the link for Apple intraday data 5min resolution:

https://tvc4.forexpros.com/c05f9748c82ced69094051303ee7cac9/1602415618/1/1/8/history?symbol=NASDAQ:AAPL&resolution=5&from=1571311623&to=1602415683"

https://tvc4.forexpros.com/c05f9748c82ced69094051303ee7cac9/1602415618/1/1/8/history?symbol=6408&resolution=5&from=1571311623&to=1602415683"
6408


As you can see, the "symbol" attribute can be a string containing the exchange and symbol (exchange:symbol) or the id.

**Comment by odufb** [comment]
thank you @alvarobartt this solution good for me but one more last question . I couldnt understand the format of FROM and TO inputs. How can I convert  begining and end dates to integer

**Comment by legout** [comment]
FROM and TO are unix timestamps.

Converting a datetime string to a unix timestamp is easy:

```
import pandas as pd
print(int(pd.Timestamp('2020-10-12').timestamp()))
```
Note: "1602415618" is also an unix timestamp. Guess which one ;-)

BTW, I am not @alvarobartt


legout

**Comment by alvarobartt** [comment]
Hi both of you @odufb and @legout!

Of course intraday data is cool and a nice to have feature, but in this package just the Investing.com features are being covered, as this is an external feature I could maybe develop a new package for intraday data from the ForexPros site you shared. Would that be a possible/valid solution for you?

Just let me know! Remember to star the repo, follow me here and on Twitter at https://twitter.com/alvarobartt so as to get notified from all the updates and projects I'm working on! ⭐ :octocat:

P.S.: will be closing this for now as this is an external feature (I guess).

**Comment by legout** [comment]
Altough this is closed, I´ll reply once again:
Another source for intraday data provided by investing.com is:

https://advcharts.investing.com/advinion2016/advanced-charts/1/1/8/GetRecentHistory?strSymbol=6408&iTop=1500&strPriceType=bid&strFieldsMode=allFields&strExtraData=lang_ID=1&strTimeFrame=15M

Regards,
legout
