### ISSUE TITLE
Fundamentals do not work

### ISSUE THREAD

**Issue by lefig** [alvarobartt/investpy#233]
These are LSE quoted stocks such as BNKR

Loaded 'runpy'
invalid literal for int() with base 10: '137.13'
Stack trace:
 >  File "C:\work\Trading\Model\lib\Tester\Tester\run_investing.py", line 12, in <module>
 >    df = investpy.stocks.get_stock_financial_summary('BNKR', country='united kingdom')

**Comment by alvarobartt** [comment]
Hi @lefig I'm currently applying some code refactoring, but I'll try to generate the v1.1 release tomorrow as that's one of the several bugs that have been fixed. 👍🏻 

Thank you for reporting it anyway!

**Comment by alvarobartt** [comment]
Hi @lefig, that has been already fixed and you can install the new release with the fix using the following command:

```bash
pip install git+https://github.com/alvarobartt/investpy.git@master
```

Hope this works for you! Closing this for now, LMK if there's something else wrong! 👍🏻
