### ISSUE TITLE
as_json=True makes the latest date truncate at 31/12/2014

### ISSUE THREAD

**Issue by GitHunter0** [alvarobartt/investpy#255]
When `as_json = True`, the latest date retrieved is truncated at 31/12/2014

For example, that happens in the two examples below:                                      
```
import investpy
investpy.get_stock_historical_data(stock='AAPL',
                                   country='united states',
                                   interval='Daily',
                                   from_date='01/01/1996',
                                   to_date='17/12/2020',
                                   order = 'descending',
                                   as_json = True)
                                     
investpy.get_index_historical_data(index='S&P 500',
                                   country='united states',
                                   interval='Daily',
                                   from_date='01/01/1996',
                                   to_date='17/12/2020',
                                   order = 'descending',
                                   as_json = True)  
```

I'm using the latest development version from "developer" branch. I tried the "master" branch too.

Thank you for your time!

My environment information:

sinfo       0.3.1
-----
IPython             7.19.0
jupyter_client      6.1.7
jupyter_core        4.7.0
-----
Python 3.9.0 | packaged by conda-forge | (default, Oct 14 2020, 22:54:35) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.19041-SP0
4 logical CPU cores, Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
-----
Session information updated at 2020-12-28 20:39

Package          Version
---------------- ---------
backcall         0.2.0
certifi          2020.12.5
chardet          4.0.0
cloudpickle      1.6.0
colorama         0.4.4
cycler           0.10.0
decorator        4.4.2
idna             2.10
investpy         1.0
ipykernel        5.3.4
ipython          7.19.0
ipython-genutils 0.2.0
jedi             0.17.2
jupyter-client   6.1.7
jupyter-core     4.7.0
kiwisolver       1.3.0
lxml             4.6.2
matplotlib       3.3.2
mpmath           1.1.0
numpy            1.19.4
olefile          0.46
pandas           1.2.0
parso            0.7.0
pickleshare      0.7.5
Pillow           8.0.1
pip              20.2.4
plotly           4.14.1
prompt-toolkit   3.0.8
Pygments         2.7.3
pyparsing        2.4.7
python-dateutil  2.8.1
pytz             2020.5
pywin32          228
pyzmq            20.0.0
requests         2.25.1
retrying         1.3.3
setuptools       51.1.0
sinfo            0.3.1
sip              4.19.13
six              1.15.0
spyder-kernels   1.10.0
stdlib-list      0.8.0
sympy            1.7.1
tornado          6.1
traitlets        5.0.5
Unidecode        1.1.2
urllib3          1.26.2
wcwidth          0.2.5
wheel            0.35.1
wincertstore     0.2

**Comment by alvarobartt** [comment]
Hi @GitHunter0, can you please check whether this issue is still happening or not? Can you share an example (input/output)? Thanks! 🤗

**Comment by GitHunter0** [comment]
Hey my friend, I just re-tested and I'm glad to share that this issue was solved in the new version 1.0.3, nice!
You can see here:
```
import investpy
import json
json_str = investpy.get_stock_historical_data(stock='AAPL',
                                   country='united states',
                                   interval='Daily',
                                   from_date='01/01/1996',
                                   to_date='23/03/2021',
                                   order = 'descending',
                                   as_json = True)
json_df = pd.read_json(json_str) 
print(json_df)
```
Just one question, `json_df` is not a properly structured pandas dataframe, what is the correct way to convert `json_str` into a dataframe?

Thank you @alvarobartt

**Comment by alvarobartt** [comment]
Hi again @GitHunter0, I'm glad that your issue is already solved! 🤗 

I'm currently working on that, so that instead of a JSON as a string the function returns a Python dictionary (which is a properly formatted JSON) when using `as_json=True`.

You should expect this to be ready later this week for the `v1.0.4` release! :fire:

**Comment by alvarobartt** [comment]
There's still a lot of room for improvement before the `v1.1.0` release comes out, as improving the code (cosmetically) will also help everyone while contributing making it easier than ever! :muscle:

**Comment by GitHunter0** [comment]
Great man, you are doing a wonderful job in `investpy`! Thanks again @alvarobartt
