### ISSUE TITLE
How can i see 1 year data

### ISSUE THREAD

**Issue by savemetherain** [alvarobartt/investpy#257]
Hi everyone, 
I just wonder how can I see 1-year data with this code.
I just want to see 1 stock of 1 year period.
I can see just 5 day period.
I'm not good at coding sorry about that. 
 
**i found the solution.
this post could be deleted.**

**Comment by savemetherain** [comment]
i did something like that but this is useless 

`import investpy
from datetime import datetime, timedelta

def vericekme(modified_date):
    df = investpy.get_stock_historical_data(stock='AAPL',
                                            country='United States',
                                            from_date=modified_date,
                                            to_date="01/01/2021")
    print(df.head())



y=1
x = "01/01/2018"
for k in range(10):
    date = datetime.strptime(x, "%d/%m/%Y")
    modified_date = date + timedelta(days=y)
    datetime.strftime(modified_date, "%d/%m/%y")
    y = y + 6
    vericekme(modified_date.strftime("%d/%m/%Y"))`

**Comment by alvarobartt** [comment]
Hi @savemetherain I'm glad you were able to find out that `data.head()` just prints the first 5 entries even though all the information is available in the data object 🤗 Feel free to ask as much questions as you need to! 👍🏻
