### ISSUE TITLE
Issues with python 3.9

### ISSUE THREAD

**Issue by faralagua** [alvarobartt/investpy#266]
I am triying to use investpy in python 3.9 and i am having a problem running my code:
import investpy
df = investpy.get_stock_historical_data(stock='AAPL',
                                        country='United States',
                                        from_date='01/01/2010',
                                        to_date='01/01/2020')
print(df.head())
just using the example that you published, and it appears this error in the console:
ImportError: cannot import name 'etree' from 'lxml' (C:\Program Files\Spyder\pkgs\lxml\__init__.py)
i tried unistalling the lxml and investpy, and installing it again in its latest version and still having the same error, if you could help me to solve this would be excellent

**Comment by alvarobartt** [comment]
Cool! Thank you for reporting it @faralagua 👍🏻 

I will tackle it next week as currently I am mad busy, but I want to include Python 3.9 support ASAP, so stay tuned as next week this issue will be most likely solved! 🤗

**Comment by alvarobartt** [comment]
Hi @faralagua! 🤗 I've just tested the installation and `pytests` with Python 3.9 and it works properly, could you please install the package from source as it follows?

``pip install git+https://github.com/alvarobartt/investpy.git@master``

Remember to star the repo, follow me here and on Twitter at https://twitter.com/alvarobartt so as to get notified from all the updates and projects I'm working on! ⭐
