### ISSUE TITLE
Spelling Mistake in indices.csv

### ISSUE THREAD

**Issue by ravidparikh92** [alvarobartt/investpy#276]
I noticed that in the indices.csv file, the spelling for Israel  in the country column is "Israel" for some indices and "Israeli" for some indices. While in the constant.py file, the spelling for Israel is listed correctly ("Israel"). This issue prevented me from downloading TA35, TA 90 and TA125 indices for Israel as for these indices the country in the "indices.csv" file was listed as "Israeli". I have fixed this in the local "indices.csv" file on my machine. I hope this update can be made on the broader distribution too.

**Comment by alvarobartt** [comment]
Thank you for spotting this error! I'll update the `indices.csv` file as soon as possible so that all those stocks are grouped together 👍🏻

**Comment by alvarobartt** [comment]
Already solved! 🤗 

To install the current development version use the following command:

```bash
pip install git+https://github.com/alvarobartt/investpy.git@master
```

Remember to star the repo, follow me here on GitHub and on Twitter at https://twitter.com/alvarobartt so as to get notified from all the updates and projects I'm working on! ⭐

**Comment by ravidparikh92** [comment]
Thank you very much
