### ISSUE TITLE
function: investpy.technical - add 1 minute interval

### ISSUE THREAD

**Issue by SladeSantos** [alvarobartt/investpy#277]
Good Morning!
Friend, would you add the 1 minute interval in the function: investpy.technical.moving_averages (name = 'EUR / USD', country = None, product_type = 'currency_cross', interval = '5mins')?

**Comment by alvarobartt** [comment]
Hi @SladeSantos! 🤗 

I can add it if it's available at Investing.com, so could you share the URL where I can check that it's available? Once I check that, if Investing.com provides that information, including it in `investpy` is trivial, so just let me know and I'll include it if possible.

BTW give it a look at [ta](https://github.com/bukosabino/ta) which is a project from @bukosabino, you may like it if you are interested on technical indicators and technical analysis. 👍🏻

**Comment by SladeSantos** [comment]
Follow the link: https://www.investing.com/currencies/eur-nzd-technical

In any currency pair there is the option of technical analysis for the interval of 1min, 5min, 15min ...

In this case, in the API we only have the option of 1min.

**Comment by alvarobartt** [comment]
Ok thanks @SladeSantos I will include this tomorrow as well as the tests so that you can start using this from the source version. I will give you more details tomorrow regarding the installation from source, so that you can just follow those steps! 👍🏻

**Comment by SladeSantos** [comment]
Right friend,
I'm waiting!

Thanks for listening!
Good Morning!

**Comment by SladeSantos** [comment]
investpy -> utils -> constant.py

INTERVAL_FILTERS = {
    '5mins': 60*5,
    '15mins': 60*15,
    '30mins': 60*30,
    '1hour': 60*60,
    '5hours': 60*60*5,
    'daily': 60*60*24,
    'weekly': 'week',
    'monthly': 'month'
}

Insert '1min' : 60,

**Comment by alvarobartt** [comment]
Ok I will include this in a couple of hours! 🤗 Thanks a lot!

**Comment by alvarobartt** [comment]
Sorry for the delay, will be tackling this today! 👍🏻 I'll generate an updated version of investpy 🔥

**Comment by alvarobartt** [comment]
Hi @fp-repo! The new investpy release is out! 🔥 To install it please use the following command:

``
pip install investpy --upgrade
``

Remember to star the repo, follow me here and on Twitter at https://twitter.com/alvarobartt so as to get notified from all the updates and projects I'm working on! ⭐ :octocat:
