### ISSUE TITLE
Bug on converting string to int value

### ISSUE THREAD

**Issue by anhanh11001** [alvarobartt/investpy#278]
`line 1435, in get_stock_financial_summary
    data[curr_row].append(int(row.text_content().strip()))`

`ValueError: invalid literal for int() with base 10: '7715168.69'`

**Comment by anhanh11001** [comment]
Already fixed

**Comment by alvarobartt** [comment]
Cool! Read the comment I left you in the PR https://github.com/alvarobartt/investpy/pull/205, where you will find all the information to fix this! 👍🏻 Releasing the v1.0.1 later today!
