### ISSUE TITLE
technical.py files shows 11 indicators but the function only returns 5

### ISSUE THREAD

**Issue by kungouf** [alvarobartt/investpy#283]
Hello

first many thanks for working and developing the library
The technical.py files shows 11 indicators but the function only returns 5 (Up to ADX)
i would be particularly be interested in CCI ( reference 6) and highs/lows(reference 8)
is that a recent limitation, as i couldnt find a related parameter (  technical_indicators(name, country, product_type, interval='daily') ) to display more indicator?

many thanks

**Comment by alvarobartt** [comment]
Hi @kungouf, thanks for your kind words about my job! I'm glad you liked it 🤗 

Regarding the issue you're mentioning I'm not sure if that's either an `investpy` issue or an Investing.com issue, as maybe they provide less information... Could you please provide me a sample call to that function and also the Investing.com URL you should expect?

Thank you!

**Comment by kungouf** [comment]
Hi @alvarobartt  you are so fast replying!

import investpy

data = investpy.technical_indicators(name='Crude Oil WTI', country='United States', product_type='commodity', interval='5mins')

print(data.head())


Thanks to your work for the community!

**Comment by alvarobartt** [comment]
Hi again @kungouf! Could you please also send me the Investing.com URL for Crude Oil USA? Big thanks! 🤗

**Comment by kungouf** [comment]
Sure here is the link where you can access to CCI and other indicators in chart !

https://m.uk.investing.com/commodities/crude-oil?utm_source=investing_app&utm_medium=share_link&utm_campaign=share_instrument

**Comment by kungouf** [comment]
You can observe that for the code sample using BBVA or apple that the result is the same (indicators displays only 5 ) thanks !

**Comment by alvarobartt** [comment]
Hi @kungouf after some tests I've just found out that you may be using `data.head()` to print the indicators, while the `.head()` function just displays the first 5 rows of a `pandas.DataFrame`, but the data is there. You can either iter through the `pandas.DataFrame` or print it, both options provided below:

```python
# Iter through the pandas.DataFrame and print the indicators
for idx, row in data.iterrows():
  print(row)

# Print the whole pandas.DataFrame
print(data)
```

Test this and whether this was your error or not, because I've tested multiple commodities technical data and it works for all of the ones that I've tried! 🤗 

Here's the result:

![imagen](https://user-images.githubusercontent.com/36760800/107117659-1e637500-687c-11eb-8418-366c4bf1da5e.png)

Hope this was useful to you! Remember to star the repo, follow me here and on Twitter at https://twitter.com/alvarobartt so as to get notified from all the updates and projects I'm working on! ⭐ :octocat:

**Comment by alvarobartt** [comment]
BTW make sure to update your package with the following command as the 1.0.1 has just released :sparkles: and contains a new interval (1min) when it comes to technical data retrieval!

```
pip install investpy==1.0.1
```

**Comment by kungouf** [comment]
Alvaro thank you so much, indeed the display function for head was not the appropriate all to access all fields of the panda.Dataframe! indeed the suggested example works and i have the latest version to get 1min interval which is just great!

 Lastly, the above give the latest technical available for the instrument. 
Which function can be used to get the price corresponding to the technical at that exact minute?

I only found the below to get daily price , but the 1 min interval is not available, so perhaps i am using the wrong function to achieve this?

import investpy

df = investpy.commodities.get_commodity_recent_data(
    commodity='Crude oil WTI', country='United States', as_json=False, order='ascending', interval='Daily')

print(df)

many thanks!

**Comment by alvarobartt** [comment]
Hi @kungouf! I'm glad this was useful to you 🤗 

Regarding the current price you can use the following piece of code, where the latest close price is the current price (if the market is still open, if it's already closed that's the close market value of that day):

```python
import investpy

data = investpy.get_commodity_recent_data(commodity='Crude oil WTI', country='United States')
current_price = data.iloc[0]["Close"]
print(current_price)
```

Remember to star the repo, follow me here and on Twitter at https://twitter.com/alvarobartt so as to get notified from all the updates and projects I'm working on! ⭐:octocat:

**Comment by kungouf** [comment]
hi thanks for the above, however in order for the calculation to be accurate the analytics and the price should be the exact one at the same time (one minute difference can represent a catastrophic gap), is there a possibility to include the current price returned with the other analytics?
 many thanks

**Comment by alvarobartt** [comment]
Not sure! Can you open a new issue where you request this? BTW you need to include the Investing.com URL of the technical indicators of any product and check whether that concrete page contains the value which has been used for that calcultion. As if Investing.com does not contain that data in the same page I would not be able to provide an exact value for the value at that time... 🤗

**Comment by kungouf** [comment]
sure i will open a new issue, i think it can definitely be retrieved from the investing page. price and analytics are both available against the streaming chart page, i will open a new issue now thanks!
