### ISSUE TITLE
crash when "fund_names" contain "tilde" get_fund_historical_data()

### ISSUE THREAD

**Issue by angel-mi-alvarez** [alvarobartt/investpy#286]
the function get_fund_historical_data() fails to retrieve data when the fund name contains a "tilde" (removing the "tilde" works fine) J

This can reproduce the issue:
df = investpy.get_fund_historical_data(fund='Renta 4 Multigestión 2 Sant Ignasi Fund Fi', country='spain',from_date='01/01/2010', to_date='01/01/2019')

This code below might help to remove the weird characters from the fund names

import re
from unicodedata import normalize
fund_name = re.sub(
        r"([^n\u0300-\u036f]|n(?!\u0303(?![\u0300-\u036f])))[\u0300-\u036f]+", r"\1", 
        normalize( "NFD", name), 0, re.I
    )
fund_name = normalize( 'NFC', name)

Regards,
Angel

**Comment by alvarobartt** [comment]
Thanks for reporting this issue @angel-mi-alvarez! I'm currently working on the v1.0.3 release, so this issue will be solved in the next days 👍🏻 The new release should be out by the end of this week! I will ping you in case I need more information but I think that this is enough to reproduce the issue. Thanks again!

**Comment by alvarobartt** [comment]
Can you also tell me which investpy version are you using?

__Tip__: `print(investpy.__version__)`

**Comment by angel-mi-alvarez** [comment]
Cool. Gracias

**Comment by alvarobartt** [comment]
Already solved @angel-mi-alvarez! BTW thanks a lot for spotting this as some other files were still containing this bug 🔥 You can install investpy from source so as to check whether this works now for you or not. Let me know it! The v1.0.3 release will be out later this week.

To install it from source please use the following command:

```
pip install git+https://github.com/alvarobartt/investpy.git@master
```

Remember to star the repository, follow me here and on Twitter at https://twitter.com/alvarobartt so as to get notified about all the updates and projects I'm working on! ⭐ :octocat:

**Comment by angel-mi-alvarez** [comment]
Hi Alvaro,

still not working for me, I followed your instructions to re-install the
updated library

pip install git+https://github.com/alvarobartt/investpy.git@master


fondo='Ubs Mixto Gestión Activa I Fi'
df2 = investpy.get_fund_recent_data(fund=fondo, country='spain')
print(df2)


---------

---------------------------------------------------------------------------RuntimeError
                             Traceback (most recent call
last)<ipython-input-3-34a3db4d0c28> in <module>      1 fondo='Ubs
Mixto Gestión Activa I Fi'----> 2 df2 =
investpy.get_fund_recent_data(fund=fondo, country='spain')      3
print(df2)
~/opt/anaconda3/lib/python3.8/site-packages/investpy/funds.py in
get_fund_recent_data(fund, country, as_json, order, interval)    259
  260     if fund not in list(funds['name'].str.lower()):--> 261
  raise RuntimeError("ERR#0019: fund " + fund + " not found, check if
it is correct.")    262     263     symbol =
funds.loc[(funds['name'].str.lower() == fund).idxmax(), 'symbol']
RuntimeError: ERR#0019: fund ubs mixto gestion activa i fi not found,
check if it is correct.




following you in Tweeter,J

by the way, are you planning to extend the functionality of investpy?


I am very very interested in helping in  getting expanded for Investment
Funds: e.g.
Some of the values are not complete, as Morningstart Rating, Category,
Issuer

investpy.get_fund_information(fund='Bbva Plan Multiactivo Moderado Pp',
country='spain')

[image: image.png]


in General Overview:
[image: image.png]
[image: image.png]
in General Holdings

Assets Allocation
[image: image.png]
[image: image.png]
[image: image.png]
And Region Allocation - this migh be challenging (not sure if the % are
around the pie charts)
[image: image.png]


if you guide me, I could significantly contribute if needed...

Regards
Angel

**Comment by alvarobartt** [comment]
Hi @angel-mi-alvarez, let me check that later 👍🏻 I checked that a couple of times but maybe I did something else! BTW I saw you sent me a previous mail but I'm not able to see it, just a slice of it, can you resend it to alvarobdc@yahoo.com or via Twitter at @alvarobartt?

I think that's because you answered to the issue from your mail and attached images, so it didn't show on GitHub 😩
