### ISSUE TITLE
AttributeError: 'PandasArray' object has no attribute '_str_lower'

### ISSUE THREAD

**Issue by gelono** [alvarobartt/investpy#290]
When trying to use the method "investpy.get_index_historical_data (index = 'S & P 500 Energy', country = 'United States', from_date = '01 / 01/2010 ', to_date = '01 / 01/2020')" I get the error:
AttributeError: 'PandasArray' object has no attribute '_str_lower'

Interestingly, everything worked fine a few days ago.

**Comment by gelono** [comment]
Problem was solved.

**Comment by alvarobartt** [comment]
Hi @gelono! So the issue is solved? Was it an `investpy` issue?

**Comment by gelono** [comment]
Yes, the issue was solved. No, this is the Pandas problem. I have downgraded the Pandas version.

**Comment by alvarobartt** [comment]
Mmm then that's interesting, what pandas version where you using if I may ask? As we may need to update the call to `str.lower()` if that's deprecated in the latest pandas version...

Either that or just fixing the pandas version (pinning the pandas version in the `requirements.txt`)!

Thanks in advance!

**Comment by gelono** [comment]
I'm sorry. I was wrong. When I was using Pandas 1.2.2 I had a problem with the "statsmodels" library. I had to downgrade Pandas to 1.1.3. After that Investpy didn't work. And then I updated Pandas to 1.1.5 and Investpy works fine.
