### ISSUE TITLE
Can't retrieve data from indices located in "euro zone" 

### ISSUE THREAD

**Issue by pourquoi42** [alvarobartt/investpy#293]
Seems there is a regression of https://github.com/alvarobartt/investpy/issues/226

I've installed investpy from master today with 
`
pip install git+https://github.com/alvarobartt/investpy.git@master
`

(I also tried it with v1.0.1 and v1.0.2)

`
`
>import investpy
>ids=investpy.indices.get_indices()
>ids[(ids["symbol"].str.contains("STOXX"))  ]
Out[5]: 
        country                       name                  full_name     symbol currency               class          market
1667  euro zone    STOXX Europe 600 EUR NR    STOXX Europe 600 EUR NR     STOXXR      EUR  additional_indices  global_indices
1905  euro zone                  STOXX 600                  STOXX 600      STOXX      EUR       major_indices  global_indices

>investpy.indices.get_index_information(index="STOXX", country="euro zone")
Traceback (most recent call last):
  File "/home/gerald/w/xetradict/ENV/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-ddd8a1769cdb>", line 1, in <module>
    investpy.indices.get_index_information(index="STOXX", country="euro zone")
  File "/home/gerald/w/xetradict/ENV/lib/python3.8/site-packages/investpy/indices.py", line 689, in get_index_information
    raise RuntimeError("ERR#0034: country " + country + " not found, check if it is correct.")
RuntimeError: ERR#0034: country euro zone not found, check if it is correct.
`

**Comment by alvarobartt** [comment]
Hi @pourquoi42! I'll check this later today and fix it 👍🏻 Can you check if this happens also for other financial products? Anyway, I'll try to fix this and include it in the `investpy v1.0.3` release.

**Comment by alvarobartt** [comment]
Sorry for taking so long to solve this issue even though it was easy to fix but I though it was already fixed 😩

Thank also @GitHunter0! He/She has been tracking this issue for so long as well as proposing solutions!

To install the latest version with this bug fix as well as some other fixes, please install it as it follows:

```
pip install investpy==1.0.3
```

Remember to star the repository, follow me here at https://github.com/alvarobartt and on Twitter at https://twitter.com/alvarobartt so as to get notified about all the updates and projects I'm working on! :star: :octocat:

**Comment by alvarobartt** [comment]
@pourquoi42 Sorry for taking so long to solve this issue even though it was easy to fix but I though it was already fixed 😩 Now both "world" and "euro zone" data retrieval is available!

To install the latest version with this bug fix as well as some other fixes, please install it as it follows:

```
pip install investpy==1.0.3
```

Remember to star the repository, follow me here at https://github.com/alvarobartt and on Twitter at https://twitter.com/alvarobartt so as to get notified about all the updates and projects I'm working on! :star: :octocat:

**Comment by GitHunter0** [comment]
@alvarobartt , for the tests I just made, the issue is solved, thank you!

**Comment by alvarobartt** [comment]
Thanks a lot for the feedback @GitHunter0! 👍🏻 Please let me know if there's any other issue
