### ISSUE TITLE
investpy.stocks.get_stock_information() API giving error for all symbols.

### ISSUE THREAD

**Issue by SLakhani1** [alvarobartt/investpy#315]
investpy.stocks.get_stock_information(stock=symbol, country='India', as_json=True) API is giving error for all symbols.
I have tried many different symbols such as BDYN, ADTB, CNBK etc.

Error-

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sl/Desktop/finacular/venv/lib/python3.6/site-packages/investpy/stocks.py", line 1133, in get_stock_information
    raise RuntimeError("ERR#0004: data retrieval error while scraping.")
RuntimeError: ERR#0004: data retrieval error while scraping.

**Comment by alvarobartt** [comment]
PR #314 solved this, and the build was fixed in 47cb1dc :muscle:
