### ISSUE TITLE
Stopped receiving technical data for the stock

### ISSUE THREAD

**Issue by guberm** [alvarobartt/investpy#326]
![image](https://user-images.githubusercontent.com/577099/113898402-d8526100-9799-11eb-9b6f-b486b9ec02cd.png)

**Comment by alvarobartt** [comment]
You can install the new-fixed version as it follows:

```bash
pip install investpy==1.0.5
```

Sorry for the inconvenience, seems that Investing.com is applying a lot of changes and under maintenance... Everyone thank both @danilogalisteu and @nhlsm for their awesome support! 👍🏻

**Comment by alvarobartt** [comment]
Feel free to drop some comments here https://github.com/alvarobartt/investpy/discussions/334 and more information if applicable, such as the IDs of the solved issues and so on, so that I can include all the information into the Release Notes! :hugs: Thank you!

**Comment by guberm** [comment]
You are amazing, thank you so much!!!
