### ISSUE TITLE
Search and data download not working

### ISSUE THREAD

**Issue by danilogalisteu** [alvarobartt/investpy#327]
MVE:

```python
import investpy as ip
res = ip.search_quotes('gold')
```
results in:
```
Traceback (most recent call last):

  File "<ipython-input-23-994b566a65ab>", line 1, in <module>
    res = ip.search_quotes('gold')

  File "D:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\investpy\search.py", line 127, in search_quotes
    data = req.json()

  File "D:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)

  File "D:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)

  File "D:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)

  File "D:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())

JSONDecodeError: Expecting value
```

I traced the problem (similar to [this](https://stackoverflow.com/questions/49702214/python-requests-response-encoded-in-utf-8-but-cannot-be-decoded)) to the fact that Investing.com is returning content compressed with [Brotli](https://en.wikipedia.org/wiki/Brotli), which is accepted according to the search headers (`search.py` line 107):
```python
    head = {
        "User-Agent": random_user_agent(),
        "X-Requested-With": "XMLHttpRequest",
        "Accept": "text/html",
        "Accept-Encoding": "gzip, deflate, br",
        "Connection": "keep-alive",
    }
```
but can't be decompressed by the requests package (`search.py` line 127):
```python
        data = req.json()
```

Additionally, the headers used to retrieve recent or historical data with a SearchObj also contain the `br` accepted encoding (`search._obj.py` lines 258 and 279), resulting on an error raised on `search._obj.py` line 155:
```
ERR#0004: data retrieval error while scraping.
```

So, the solution is to either add `brotli` as a package requirement and register the decoder with `requests`, or remove the `br` accepted encoding in `search.py` line 111, `search._obj.py` lines 258 and 279, and others as required.

**Comment by alvarobartt** [comment]
You can install the new-fixed version as it follows:

```bash
pip install investpy==1.0.5
```

Sorry for the inconvenience, seems that Investing.com is applying a lot of changes and under maintenance... Everyone thank both @danilogalisteu and @nhlsm for their awesome support! 👍🏻

**Comment by alvarobartt** [comment]
Feel free to drop some comments here https://github.com/alvarobartt/investpy/discussions/334 and more information if applicable, such as the IDs of the solved issues and so on, so that I can include all the information into the Release Notes! :hugs: Thank you!
