### ISSUE TITLE
Data retrieved from SearchObj is overwritten with None

### ISSUE THREAD

**Issue by danilogalisteu** [alvarobartt/investpy#333]
In `search_obj.py` method `_convert2df`, the result is overwritten with None due to an `inplace` argument.

**Comment by typhoon71** [comment]
I can confirm the fix solves the issue; this is breaking investpy badly and I suggest a quick release to push this fix.
I corrected it myself locally once I read what it was, but a hotfix should be preferred for the masses.
Good job danilogalisteu spotting the cause, it's a stupid error I sometime do myself too (forgetting inplace methods are... inplace).

**Comment by alvarobartt** [comment]
Thanks a lot @danilogalisteu! :fire: You rock!

Hi @typhoon71, thanks for confirming that it works as expected, I'm merging it ASAP so as to release `investpy v1.0.5`. Stay tuned, and sorry for the inconvenience...

**Comment by alvarobartt** [comment]
You can now install the latest `investpy` release as it follows:

```bash
pip install investpy==1.0.6
```

Thanks for the support! :muscle::fire:
