### ISSUE TITLE
get_currency_cross_historical_data produces ERR#0004: data retrieval error while scraping

### ISSUE THREAD

**Issue by ymyke** [alvarobartt/investpy#337]
The `get_currency_cross_historical_data` function seems to no longer work:

`investpy.get_currency_cross_historical_data(currency_cross='EUR/USD', from_date='01/01/2018', to_date='01/01/2019')`

produces:

`RuntimeError: ERR#0004: data retrieval error while scraping.`

Any ideas? Did something change on Investing's end?

**Comment by ymyke** [comment]
Never mind. I wasn't on the latest version. The issue is fixed in the latest commit. Sorry for this.

**Comment by alvarobartt** [comment]
No worries @ymyke, indeed there was another issue that required a quick bug fix, as the data retrieved over the `SearchObj` in `investpy.search_quotes` was being overwritten, so that you need to update investpy again as it follows:

```bash
pip install investpy==1.0.6
```

Thank you and sorry for the inconvenience!

**Comment by ymyke** [comment]
Thanks, I found that one as well and fixed it locally for the time being  when I saw there is a PR pending. ;-)
