### ISSUE TITLE
Failed to scrap stock data

### ISSUE THREAD

**Issue by snvv** [alvarobartt/investpy#355]
Hello
I tried today to download stock prices and the program failed with the following message:

Traceback (most recent call last):

  File "/home/sotnik/untitled0.py", line 19, in <module>
    df = investpy.get_stock_recent_data(stock='bbva', country='spain', as_json=False, order='ascending')

  File "/home/sotnik/.local/lib/python3.9/site-packages/investpy/stocks.py", line 346, in get_stock_recent_data
    raise RuntimeError("ERR#0004: data retrieval error while scraping.")

I upgraded investpy to the latest version but the problem remains.

It used to work without any problem.

Is something that I can do about this?

Thank you
Sotiris

**Comment by milesziemer** [comment]
Experiencing the same issue

**Comment by Giezzy** [comment]
I tried making requests directly and I'm getting 403 errors (maybe investing is forbidding the searches?)

**Comment by alvarobartt** [comment]
BTW another option may be that the stock that you are querying is failing, so please can you all share the code that you used so that I can reproduce the issue? Thanks again 👍🏻

**Comment by snvv** [comment]
Thank you alvarobartt
The problem was the old investpy version in my PC.
In fact the problem caused from minicoda.
Regards
Sotiris
