### ISSUE TITLE
ERR#0015: error 503, try again later

### ISSUE THREAD

**Issue by aktastunc** [alvarobartt/investpy#364]
Hello,

I have been using same code for almost a year. But nowadays I am getting below error code:

"ERR#0015: error 503, try again later"

I tried simple examples from the documentation but couldn't get any result. If you can help me, I would be very pleased. I also attached a screenshot from the error of a simple code.
<img width="583" alt="Screenshot" src="https://user-images.githubusercontent.com/83545280/116817561-94bbfe80-ab6f-11eb-8413-1e5bcf2908b8.png">

**Comment by MaximilianSoeren** [comment]
Hey there, I have been developing with investpy recently too, and I started getting this error as well. Even after just one request through investpy.get_stocks_dividends() it already gives me this error. Maybe this is a new one?

**Comment by caiovms** [comment]
I believe there is something wrong indeed, I am getting the same error:

![image](https://user-images.githubusercontent.com/5957094/117056255-7c282180-acf2-11eb-9028-0ee7ca266c2b.png)

**Comment by volantines** [comment]
¿Investing API it's down?

https://www.investing.com/instruments/HistoricalDataAjax

![image](https://user-images.githubusercontent.com/4184186/117062939-163b9a00-acf2-11eb-8530-d57ffbb1dfe7.png)

**Comment by LuccaPrado** [comment]
Investing.com is really unstable/almost off the entire day today... It would be nice if we had some "caching" on the client side, as situations like that wouldn't be so frequent and impacting.

**Comment by alvarobartt** [comment]
Hi everyone @volantines, @LuccaPrado, @aktastunc, @caiovms, and @MaximilianSoeren :hugs:

As some of you say, Investing.com was experiencing some errors yesterday, but today it seems to be working fine! There's really nothing I can do with that as I'm not related to Investing.com at all so there's nothing I can do to solve this or cache the data as some of you suggested...

I'll include some functions to check the Investing.com API status so that you can check whether the error is on the client-side or on the server-side!

**Comment by alvarobartt** [comment]
BTW this has happened a few times during 2021, nothing too critical, as AFAIK Investing.com is updating the API, but I'm not aware of which changes, etc.

I'll be ready to keep `investpy` up to date so that it's as consistent as possible! :muscle:

**Comment by LuccaPrado** [comment]
> Hi everyone @volantines, @LuccaPrado, @aktastunc, @caiovms, and @MaximilianSoeren :hugs:
> 
> As some of you say, Investing.com was experiencing some errors yesterday, but today it seems to be working fine! There's really nothing I can do with that as I'm not related to Investing.com at all so there's nothing I can do to solve this or cache the data as some of you suggested...
> 
> I'll include some functions to check the Investing.com API status so that you can check whether the error is on the client-side or on the server-side!

@alvarobartt what I said about caching is on client side, like, I get the funds information and the data is stored on my machine, so that, if the next call to the same endpoint fails, it can show the locally saved previous data with some anotation that It could be old.

**Comment by alvarobartt** [comment]
Sure @LuccaPrado, thanks for the proposal! Please from now on, track this issue in https://github.com/alvarobartt/investpy/issues/353 :hugs:

I'll get back to it once I complete the upcoming release!
