### ISSUE TITLE
_recent_data does not give close, but price

### ISSUE THREAD

**Issue by enghseb** [alvarobartt/investpy#375]
After experimenting with getting the close for US10Y, I've come to the conclusion that the information shown when using:
investpy.bonds.get_bond_recent_data("U.S 10Y", as_json=False, order='ascending', interval='Daily')

Is not the close, but rather the value that's shown on the following page as "price":
https://www.investing.com/rates-bonds/u.s.-10-year-bond-yield-historical-data

While it'd make sense for price and close to be the same value, they are not. The "price" does not match the "Prev. Close" value that can be found on the overview page here:
https://www.investing.com/rates-bonds/u.s.-10-year-bond-yield

I'm guessing this is the case for more type of instruments than bonds.

The only way I've managed to obtain the latest close price, is by using investpy.bonds.get_bonds_overview(country, as_json=False)

**Comment by alvarobartt** [comment]
Hi @enghseb, you are right! :hugs:

I'll change that so that the output does not contain `Close` but `Price` as well as the `Change %` as that's more accurate! So sorry in advance, I didn't even realize... I'll try to solve this later this week.

**Comment by alvarobartt** [comment]
BTW I think that the same happens with `investpy.search_quotes` when retrieving data from bonds, as well as in `investpy.get_bond_historical_data` :+1:

**Comment by alvarobartt** [comment]
Hi @enghseb I've been exploring this issue, and it seems that Investing.com changed the column name so that now instead of `Close` the column name is `Price`, I guess that changing from `Close` to `Price` is a major change since a lot of people is using `investpy` right now... :confused:

Anyway, what I'll do is including the `Change Pct` value since it is currently missing, if you have a more detailed explanation on why did the name change from `Close` to `Price` just let me know!

Thank you!

**Comment by alvarobartt** [comment]
All this new features will be available in the next `investpy` release which will be `v1.0.7` and will come later this weekend :fire:

Stay tuned in the milestone so as to check the progress of all the issues/bugs/features that will be tackled during this sprint at https://github.com/alvarobartt/investpy/milestone/2

**Comment by alvarobartt** [comment]
Here's a list with all the supported financial products from Investing.com and the historical/recent data they provide for each type of product:

- Stocks:https://www.investing.com/equities/apple-computer-inc-historical-data
- ETFs: https://www.investing.com/etfs/spdr-s-p-500-historical-data
- Commodities: https://www.investing.com/commodities/gold-historical-data
- Currency Crosses: https://www.investing.com/currencies/eur-usd-historical-data
- Funds: https://www.investing.com/funds/vanguard-500-index-admiral-historical-data
- Bonds: https://www.investing.com/rates-bonds/u.s.-30-year-bond-yield-historical-data
- Cryptos: https://www.investing.com/crypto/bitcoin/btc-usd-historical-data
- Certificates: https://www.investing.com/certificates/sg-ftse-mib-gross-tr-5x-s-18jun21-historical-data
- Indices: https://www.investing.com/indices/us-spx-500-futures

**Comment by alvarobartt** [comment]
Hi @enghseb, the new release is already out! :fire:

You can already install it using either ``pip install investpy==1.0.7`` or just update the current version that you are using with ``pip install investpy --upgrade``. Thanks a lot for your support! :+1:

For more information about this new release, you should check [investpy v1.0.7 Release](https://github.com/alvarobartt/investpy/releases/tag/1.0.7) :balloon:
