### ISSUE TITLE
Ignore Weekend

### ISSUE THREAD

**Issue by caiovms** [alvarobartt/investpy#376]
Hello everyone, in my business, I need to obtain data from various indexes, for each day, within a range of dates.

I noticed that some indexes, like others for example, return data for the weekends, others like dollar, ignore the weekends.

I didn't find anything in the documentation that was related to this, so I leave the question:

Is there a parameter that you can skip data on weekends?

If not, do we have something on the radar for future implementations?

Thanks in advance.

**Comment by alvarobartt** [comment]
Hi @caiovms, I saw that you already closed this issue, did you find the answer? If so, could you explain it?

As I think it may be useful for other `investpy` users! :hugs:

**Comment by caiovms** [comment]
Hello @alvarobartt, actually I didn't find anything, despite finding a relevant feature, I decided to deal with it on this side, but I think it's relevant to have parameters in investpy related to calendars and weekends...
