### ISSUE TITLE
Create technical data from cryptos

### ISSUE THREAD

**Issue by sjborque** [alvarobartt/investpy#391]
To get technical values ​​with investpy:
data = investpy.technical_indicators (name = 'bbva', country = 'spain', product_type = 'stock', interval = 'daily')
data.head ()
Is it possible to get technical data from cryptos? Bitcoin, Cardano, etc.
What parameters should be indicated?

Thanks

**Comment by alvarobartt** [comment]
Already discussed in https://github.com/alvarobartt/investpy/discussions/387 and properly described in https://github.com/alvarobartt/investpy/issues/392 (for ETFs but it also applied to cryptos and all the financial products available at Investing.com) :sparkles:

**Comment by alvarobartt** [comment]
Hi @sjborque I'm glad to inform you that this feature has already been developed in the `dev` branch as part of the current milestone before the `investpy v1.0.7` release, so this feature will be available later this weekend so you just need to stay tuned for updates :fire:

The intended usage of this new functionality integrated with `investpy.search_quotes()` will be as it follows:

```python
>>> import investpy
>>> data = investpy.search_quotes('bbva', products=['funds'], n_results=1)
>>> tech = data.retrieve_technical_indicators()
>>> tech
              indicator           signal     value
0               RSI(14)              buy   61.0810
1            STOCH(9,6)          neutral   48.7880
2          STOCHRSI(14)       overbought  100.0000
3           MACD(12,26)          neutral    0.0000
4               ADX(14)       overbought  100.0000
5           Williams %R       overbought    0.0000
6               CCI(14)       overbought  215.0252
7               ATR(14)  less_volatility    0.0053
8        Highs/Lows(14)              buy    0.0172
9   Ultimate Oscillator       overbought   72.1490
10                  ROC              buy    2.2470
11  Bull/Bear Power(13)              buy    0.0316
```

__Note__ that the previous function `investpy.technical_indicators()` was retrieving those indicators based on the static files information, that is a little bit outdated, so using `investpy.search_quotes()` you'll get the latest information for every single financial product available in Investing.com. Also note that previously the column containing the technical indicator name was named `'technical_indicator'` whilst now it's been renamed to `'indicator'`.

__Thanks for your support! :+1:__

**Comment by alvarobartt** [comment]
Here's the custom example for the feature you were asking about in the issue! :fire:

```python
>>> import investpy
>>> search_result = investpy.search_quotes(text='bitcoin', products=['cryptos'], n_results=1)
>>> print(search_result
... )
{"id_": 945629, "name": "Bitcoin US Dollar", "symbol": "BTC/USD", "country": "bitcoin", "tag": "/crypto/bitcoin/btc-usd", "pair_type": "cryptos", "exchange": "Bitfinex"}
>>> tech = search_result.retrieve_technical_indicators()
>>> tech
              indicator           signal      value
0               RSI(14)             sell    41.9740
1            STOCH(9,6)       overbought    87.8760
2          STOCHRSI(14)              buy    69.5120
3           MACD(12,26)             sell -2628.8000
4               ADX(14)             sell    32.1250
5           Williams %R       overbought   -12.1470
6               CCI(14)          neutral    -6.1757
7               ATR(14)  less_volatility  2220.5841
8        Highs/Lows(14)          neutral     0.0000
9   Ultimate Oscillator              buy    54.1110
10                  ROC              buy     3.1560
11  Bull/Bear Power(13)             sell  -147.0260
```

__Release will be live either later today or tomorrow. Stay tuned! :+1__

**Comment by alvarobartt** [comment]
Hi @sjborque, the new release is already out! :fire:

You can already install it using either ``pip install investpy==1.0.7`` or just update the current version that you are using with ``pip install investpy --upgrade``. Thanks a lot for your support! :+1:

For more information about this new release, you should check [investpy v1.0.7 Release](https://github.com/alvarobartt/investpy/releases/tag/1.0.7) :balloon:

**Comment by sjborque** [comment]
Thank you. It works great. All the best !
