### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by shru-tea** [alvarobartt/investpy#400]
The new documentation of latest version of investpy lacks proper details regarding various APIs related to funds and equities data.
It would be of great help if the document gets updated as quick as possible.
Thanks

**Comment by alvarobartt** [comment]
Hi @shru-tea, can you provide me more information? Previously I had some extra pages specifically for stocks/equities and funds, but I removed those since the information there was somehow redundant, but I can create a new version of those for every single financial product available at Investing.com, would that work for you? :hugs:

**Comment by shru-tea** [comment]
Hello,
Thanks for the quick reply. I would like to give you an example if that is alright.
search_results = investpy.search_quotes(text='1nf251k01985',countries=['India'],products=['funds'])
for search in search_results: print(search) => I am getting the following information==> {id,name,symbol,country,as_json)
Now if I am using the same name which is being sent back to me using the above command(name='Bnp Paribas Long Term Equity Fund Growth') and when I am putting it in the following command, I get an error saying to check if it is correct or not.
data=investpy.get_fund_information(fund='Bnp Paribas Long Term Equity Fund Growth',country='india',as_json=True)

Another issue, 
https://in.investing.com/equities/ganesha-ecosphere-ltd
We do have this data on investing but when I run the following command, 
stocks=investpy.stocks.get_stock_information(stock='GANS',country='India',as_json=True)
ERR#0018: stock gans not found, check if it is correct.

Please help if there has bee any changes that the documentation does not contain yet.

**Comment by alvarobartt** [comment]
Hi @shru-tea, this issue has already been solved, now the [Developer API Reference](https://investpy.readthedocs.io/api.html) is available again! :+1:

**Comment by alvarobartt** [comment]
BTW @shru-tea can you report this in a new issue? Thanks!

> 
> 
> Hello,
> Thanks for the quick reply. I would like to give you an example if that is alright.
> search_results = investpy.search_quotes(text='1nf251k01985',countries=['India'],products=['funds'])
> for search in search_results: print(search) => I am getting the following information==> {id,name,symbol,country,as_json)
> Now if I am using the same name which is being sent back to me using the above command(name='Bnp Paribas Long Term Equity Fund Growth') and when I am putting it in the following command, I get an error saying to check if it is correct or not.
> data=investpy.get_fund_information(fund='Bnp Paribas Long Term Equity Fund Growth',country='india',as_json=True)
> 
> Another issue,
> https://in.investing.com/equities/ganesha-ecosphere-ltd
> We do have this data on investing but when I run the following command,
> stocks=investpy.stocks.get_stock_information(stock='GANS',country='India',as_json=True)
> ERR#18: stock gans not found, check if it is correct.
> 
> Please help if there has bee any changes that the documentation does not contain yet.
