### ISSUE TITLE
happening much more often - ERR#0093: no results found on Investing for the introduced text.

### ISSUE THREAD

**Issue by vrancovich** [alvarobartt/investpy#434]
Hi, and hopefully this is the right venue for this. I have been using investpy for several months and I think its great. It used to be that every once in a while investpy could not find a stock using the search but now its happening all the time with stocks that used to work before with no issues.

simbolos=["DOW","AAPL","MSFT","WISH","NTLA"]

for simbolo in simbolos:
    search_result = investpy.search_quotes(text=simbolo, products=['stocks'], countries=['united states'], n_results=1)
    index=simbolos.index(simbolo)
    print(simbolo, simbolos[index:index+2])

I wrote the code above to aid me in finding which symbols are failing and if you run it on your end you will notice it fails on NTLA.

any input is appreciated.

**Comment by brianivander** [comment]
Any updates on this? I'm having the same problem

**Comment by alvarobartt** [comment]
Hi @vrancovich sorry for responding so late to this issue, I don't have too much time lately :weary: Regarding the issue that you mentioned with `investpy.search_quote` function as its using Investing.com Search Engine, I assume the issue may be on their side, anyway, let me check!

I'll report you both @vrancovich and @brianivander back once I figure out what can be happening!

**Comment by alvarobartt** [comment]
Ok so I've just tested it and it seems to be working on my side...

![image](https://user-images.githubusercontent.com/36760800/154433654-017bd593-fc6a-41c7-af03-5dbd0f7ac5dc.png)

Can you please provide me with more details on what's the exception that is being thrown? As well as more details such as the `investpy` version that you're using, your Python version, etc. Thanks!
