### ISSUE TITLE
Youtube 

### ISSUE THREAD

**Issue by Santunav** [alvarobartt/investpy#506]
Hi 
Thankful to API. 
Working great. 

Can I use this api to for creating YouTube video. 
Do I need to get copyright approval ? 

Thanks

**Comment by alvarobartt** [comment]
Hi, @Santunav feel free to use `investpy` as much as you want, and I'd love to watch the video once you upload it in case it's public! Thanks for the support ✨

**Comment by Santunav** [comment]
@alvarobartt 

Thank you. Here is the video where I'm using investpy libraries . 
Slide Indices and currency i'm using . I will try to use almost all slides. 

https://youtu.be/I7bmJ3Duqxk

still I see some gaps in this library .I am opening other tickets. 

Thank you

**Comment by alvarobartt** [comment]
Yes indeed you're right, there's a lot of things to improve on `investpy`... Hopefully, I have enough time to tackle them all! 💪🏻

**Comment by Santunav** [comment]
Thanks you have the will power, Let me know if I can support in any way .
