### ISSUE TITLE
Data retrieval error while retriving index information 

### ISSUE THREAD

**Issue by Santunav** [alvarobartt/investpy#509]
investpy.indices.get_index_information(index='Nifty IT', country='india', as_json=False)
----------------------------------------------------------------------------------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_7399/1989462206.py in <module>
----> 1 investpy.indices.get_index_information(index='Nifty IT', country='india', as_json=False)

~/.local/lib/python3.8/site-packages/investpy/indices.py in get_index_information(index, country, as_json)
    762             return result
    763     else:
--> 764         raise RuntimeError("ERR#0004: data retrieval error while scraping.")
    765 
    766 

RuntimeError: ERR#0004: data retrieval error while scraping.

**Comment by alvarobartt** [comment]
Hi @Santunav, I've just tested it and it seems to be working fine on my side... :weary: Let me check if I can reproduce the issue somehow...

![image](https://user-images.githubusercontent.com/36760800/150824529-823fa63a-54bd-4fcc-85ea-4ad1539cbc4b.png)

**Comment by alvarobartt** [comment]
@Santunav can you please make sure that you're using the latest `investpy` version (actually v1.0.7)?

**Comment by alvarobartt** [comment]
Just to let you know, the bug that you're reporting was already reported at https://github.com/alvarobartt/investpy/pull/454, and fixed at https://github.com/alvarobartt/investpy/commit/b28401226dabab91cf2227d84620341c0d307410

**Comment by alvarobartt** [comment]
Ok, it was fixed at some point but not released yet, so I'll just release `investpy v1.0.8` including some bug fixes so that you can use that function as expected! Sorry for the inconvenience :smile:

**Comment by alvarobartt** [comment]
Please try to install the latest version as detailed in https://github.com/alvarobartt/investpy/releases/tag/1.0.8 so as to check whether the bug you mentioned here is already solved or not! 👍🏻 Thanks!

**Comment by alvarobartt** [comment]
Thanks a lot @typhoon71 :hugs:

**Comment by Santunav** [comment]
Thank you for your response and quick fix.😀
